# Generated by Django 3.1.7 on 2021-03-09 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('format', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('genre', models.CharField(max_length=100)),
                ('released', models.CharField(max_length=100)),
            ],
        ),
    ]
