# Generated by Django 3.1.7 on 2021-03-14 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_played'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningBrush',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='played',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='record',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='played',
            name='date',
            field=models.DateField(verbose_name='Date Record Was Played'),
        ),
        migrations.AddField(
            model_name='record',
            name='cleaning_brush',
            field=models.ManyToManyField(blank=True, to='main_app.CleaningBrush'),
        ),
    ]
